# Generated by Django 5.0.4 on 2024-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gender',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
