# Generated by Django 5.0.4 on 2024-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_specializations_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
