# Generated by Django 5.0.4 on 2024-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_medicalrecord_date_remove_medicalrecord_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
